package icl

import "fmt"

type prefixParser func() Node

type Parser struct {
	lex *Lexer

	errors    []error
	curToken  Token
	peekToken Token

	prefixParsers map[TokenType]prefixParser
}

// New creates a new parser for the provided lexer
func NewParser(lex *Lexer) *Parser {
	p := &Parser{
		lex:           lex,
		prefixParsers: make(map[TokenType]prefixParser),
	}

	p.registerPrefixParser(TknIdent, p.parseIdentifier)
	p.registerPrefixParser(TknInt, p.parseNumberNode)
	p.registerPrefixParser(TknNull, p.parseNullNode)
	p.registerPrefixParser(TknTrue, p.parseBooleanNode)
	p.registerPrefixParser(TknFalse, p.parseBooleanNode)
	p.registerPrefixParser(TknString, p.parseStringNode)
	p.registerPrefixParser(TknLBracket, p.parseArrayNode)
	p.registerPrefixParser(TknLBrace, p.parseMapNode)

	// populate cur/next token fields
	p.nextToken()
	p.nextToken()

	return p
}

// ParseProgram parses the tokens in the lexer into an AST
func (p *Parser) Parse() *Ast {
	program := &Ast{}

	for p.curToken.Type != TknEof {
		stmt := p.parseNode()
		if stmt != nil {
			program.Nodes = append(program.Nodes, stmt)
		}

		p.nextToken()
	}

	return program
}

// Errors returns a slice of errors generated by the parser
func (p *Parser) Errors() []error {
	return p.errors
}

// registerPrefixParser registers a prefix parser funcion for the token type
func (p *Parser) registerPrefixParser(tknType TokenType, parser prefixParser) {
	p.prefixParsers[tknType] = parser
}

func (p *Parser) errorf(format string, args ...any) {
	lineKey := fmt.Sprintf(" -- [line(%d) pos(%d)]", p.peekToken.Line, p.peekToken.Pos)
	p.errors = append(p.errors, fmt.Errorf(format+lineKey, args...))
}

// nextToken advances the lexer to the next token
func (p *Parser) nextToken() {
	p.curToken = p.peekToken
	p.peekToken = p.lex.NextToken()
}

// parseNode parses the next statement in the lexers token stream
func (p *Parser) parseNode() Node {
	switch p.curToken.Type {
	case TknIdent:
		if p.peekTokenIs(TknLBrace) || p.peekTokenIs(TknIdent) || p.peekTokenIs(TknString) {
			return p.parseBlockNode()
		}
		return p.parseAssignNode()
	case TknComment:
		return nil
	default:
		return p.parseExpression()
	}
}

// peekTokenIs checks if the next token in the stream is of the provided type
func (p *Parser) peekTokenIs(tknType TokenType) bool {
	return p.peekToken.Type == tknType
}

// curTokenIs checks if the current token is of the given type
func (p *Parser) curTokenIs(tknType TokenType) bool {
	return p.curToken.Type == tknType
}

// peekError checks that the next token is of the given type
// if not then an error will be generated
func (p *Parser) peekError(tknType TokenType) (err error) {
	if !p.peekTokenIs(tknType) {
		p.errorf("Unexpected token type: expected(%s) found(%s)", tknType, p.peekToken.Type)
	}

	return
}

// expectPeek runs the peekError method and advances the token streabm if no erro is found
func (p *Parser) expectPeek(tknType TokenType) bool {
	if p.peekError(tknType) != nil {
		return false
	}

	p.nextToken()
	return true
}
